apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spicedb-service-monitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  jobLabel: job
  namespaceSelector:
    matchNames:
    - spicedb
  selector:
    matchLabels:
      app: spicedb
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 15s