apiVersion: v1
kind: Secret
metadata:
  name: spicedb-datastore
type: Opaque
stringData:
  spicedb_datastore_connection_password: yPsw5e6ab4bvAGe5H
  spicedb_datastore_connection_username: postgres
  spicedb_datastore_database_name: spicedb
  spicedb_datastore_conn_uri: postgres://postgres:yPsw5e6ab4bvAGe5H@postgres:5432/spicedb?sslmode=disable
