apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: spicedb
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: yPsw5e6ab4bvAGe5H
  POSTGRES_DB: spicedb
